language: python
services: mongodb
python:
  - "3.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-openbabel
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy
  - source activate testenv
  - conda install -q -c openbabel openbabel
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install python-coveralls
before_script:
  - python setup.py develop
script:
  - nosetests --nocapture --with-coverage --cover-package=emmet
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - dwinston@lbl.gov
      - shyamd@lbl.gov
      - montoyjh@lbl.gov
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: dwinston
  distributions: sdist bdist_wheel
  password:
    secure: NzAv0Icu+7M1V+sTqOygCVu9jdk+KNr7s0wo/2nwEpwONTlpVLBYR2lZzNDaQUhfZ37j5I11lN4V1k+O42uSE4m8iu4BevZ8JVqB7WJQXSl/KeFZOfwJYopbgXtPk6Y6NGcqnnFOzS2XNs7XLvY9jmM1DEFXQJlJcgFM05BjdCYU2rhLO8KEsh8g8KJHpgxLBlAT6rtPI1UgERcYCme45cP7qsQFV8Sl8TPCa61Vaw1yLJM83exRCYzMRF/dVNzegrzdC1OLgGIJ8CgcK12SDNSoM09NrgqlzUYWRCimUWun/L/JFHlDrKBazMoa1bFQO0nbn5hADn3sYKfMwspcegQIUgURnwzOBgvrJa7nQiJxYJvcVRxXZWB2LfL4QvoJop2Qo3AMXJi8a80Q5IlSSJk6Ik1KntqHnsKIESox5qirLmwXSGntMFIOwcaR+heJxn9p+K+I653sye5Hb0YfXSmTsFTZuW9FiNxYxmTBCFokJl4JaohdkF/SOEYJK65afGyG3H5LLaYjLPzsfkLiuNAJMS0MllvJM7ZXk9OlMsoOrMY7Dii5Fx+btkSb/rxRHNTfNy7nPJpa7cG0WOBwolAWIExwC/OxF2ebbI/OG+08llZgJGcZotn2yBmZI5kElExiSWU4acd1ZmM7uoXNgjf2Hinx4uZeSImgWMfGfho=
  on:
    tags: true
